pygame 2.5.2 (SDL 2.28.2, Python 3.11.0)
Hello from the pygame community. https://www.pygame.org/contribute.html

<Wire[16]> got called by <Religator[17]: (Closed, None, None)> with energy and no fault
old[0] -> new[1]
[<self_healing_visualizer.util.global_clock.Scheduler object at 0x7f81ad7a0d90>] [<self_healing_visualizer.util.global_clock.Scheduler object at 0x7f81b00fa590>]
1 True
Propagating to [<Charge[15]: [['Wire(14)', 'Wire(16)']]>]

<Charge[15]> got called by <Wire[16]> with energy and no fault
old[0] -> new[1]
[] [<self_healing_visualizer.util.global_clock.Scheduler object at 0x7f81ad7a0d90>, <self_healing_visualizer.util.global_clock.Scheduler object at 0x7f81ad7a1650>]
At fault, Wire[2]
[] [<self_healing_visualizer.util.global_clock.Scheduler object at 0x7f81ad7a2650>]
